# -*- coding: utf-8 -*-
"""YOLO_v5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZjIgaHdArFcUMUSWVgkxaWSSNwQu1Sq
"""

# Commented out IPython magic to ensure Python compatibility.
# Clone the YOLOv3 repository
!git clone https://github.com/ultralytics/yolov3

# Move to the YOLOv3 directory
# %cd yolov3

# Install dependencies
!pip install -U -r requirements.txt

!python train.py --img-size 416 --batch-size 16 --epochs 5 --data /content/drive/MyDrive/sample_dataset.yaml --cfg ./models/yolov3.yaml --weights yolov3.pt

from google.colab import drive
drive.mount('/content/drive')











